Repository legend-exp/remage, pull requests merged in 2024-12, with the labels that each got.

#182 Add distance to nearest surface field to GermaniumOutputScheme
  include/RMGGermaniumDetector.hh
  src/RMGGermaniumDetector.cc
  src/RMGGermaniumOutputScheme.cc
  tests/output/macros/ntuple-flat.hdf5ls
  tests/output/macros/ntuple-flat.hdf5ls-lh5
  tests/output/macros/ntuple-per-det-vol.hdf5ls
  tests/output/macros/ntuple-per-det-vol.hdf5ls-lh5
  tests/output/macros/ntuple-per-det.hdf5ls
  tests/output/macros/ntuple-per-det.hdf5ls-lh5
Labels: output

#201 Setup dummy X server for CI tests
  .github/workflows/main.yml
  tests/basics/macros/vis-2nbb.mac
  tests/basics/macros/vis-co60.mac
  tests/confinement/macros/_init.mac
  tests/confinement/macros/_vis.mac
  tests/confinement/macros/complex-volume.mac
  tests/confinement/macros/geometrical-and-physical.mac
  tests/confinement/macros/geometrical-or-physical.mac
  tests/confinement/macros/geometrical.mac
  tests/confinement/macros/native-surface.mac
  tests/confinement/macros/native-volume.mac
Labels: validation

#202 Update developer's guide
  .github/CONTRIBUTING.md
  README.md
  docs/developer.md
Labels: documentation

#211 Add .git_archival.txt
  .git_archival.txt
  .gitattributes
Labels: enhancement

#212 change IsInside check for UnionAll to act only on the selected solid not the full collection.
  CMakeLists.txt
  include/RMGVertexConfinement.hh
  src/RMGVertexConfinement.cc
Labels: bug

#210 Infrastructure for Python wrapper
  .gitignore
  CMakeLists.txt
  cmake/cpp_config.py.in
  docs/CMakeLists.txt
  docs/developer.md
  docs/index.md
  pyproject.toml
  python/CMakeLists.txt
  python/remage/__init__.py
  python/remage/cli.py
  python/remage/cpp_config.py
  src/CMakeLists.txt
  tests/CMakeLists.txt
  tests/basics/CMakeLists.txt
  tests/confinement/CMakeLists.txt
  tests/output/CMakeLists.txt
  tests/python/CMakeLists.txt
  tests/vertex/CMakeLists.txt
Labels: enhancement

#214 setup for running Python scripts in unit tests
  docs/developer.md
  pyproject.toml
  python/CMakeLists.txt
  tests/CMakeLists.txt
  tests/germanium/CMakeLists.txt
  tests/germanium/gdml/geometry.gdml
  tests/germanium/gdml/geometry.py
  tests/germanium/macros/run.mac
  tests/germanium/test_brem.py
  tests/germanium/test_e_range.py
Labels: enhancement

#217 fix problem with prettier destroying `:::{}:::` in markdown
  .pre-commit-config.yaml
  docs/developer.md
  docs/tutorial.md
Labels: bug, documentation
