Repository legend-exp/remage, pull requests merged in 2025-05, with the labels that each got.

#346 remove realms functionality
  docs/rmg-commands.md
  include/RMGPhysics.hh
  src/RMGPhysics.cc
Labels: physics

#363 gipert/remage-base has moved to legendexp/remage-base
  .dockerhub/Dockerfile
  .github/workflows/main.yml
  docs/_dependencies.md
Labels: documentation, build-system

#362 Fixes to LH5 post-processing code
  python/remage/cli.py
  python/remage/utils.py
Labels: output

#366 python: cannot merge/reshape for non-LH5 formats
  python/remage/cli.py
Labels: bug, python-wrapper

#364 More generator docs!
  .pre-commit-config.yaml
  docs/index.md
  docs/manual/extend.md
  docs/manual/generators.md
  docs/manual/index.md
  docs/manual/install.md
  pyproject.toml
Labels: documentation

#368 update the default pars
  docs/manual/output.md
  include/RMGGermaniumOutputScheme.hh
  include/RMGScintillatorOutputScheme.hh
  python/remage/cli.py
  src/RMGGermaniumOutputScheme.cc
  src/RMGScintillatorOutputScheme.cc
Labels: physics

#370 turn on output reshaping by default
  pyproject.toml
  python/remage/cli.py
  tests/confinement/CMakeLists.txt
  tests/distances/CMakeLists.txt
  tests/distances/test_ge_distance.py
  tests/nist/run_e_sims.py
  tests/observables/CMakeLists.txt
  tests/observables/run_sim.py
  tests/output/CMakeLists.txt
  tests/output/macros/ntuple-flat-with-tracks.hdf5ls-lh5
  tests/output/macros/ntuple-flat.hdf5ls-lh5
  tests/output/macros/ntuple-per-det-auto-jag.hdf5ls-lh5
  tests/output/macros/ntuple-per-det-jag.hdf5ls-lh5
  tests/output/macros/ntuple-per-det-vol-auto-jag.hdf5ls-lh5
  tests/output/macros/ntuple-per-det-vol-jag.hdf5ls-lh5
  tests/output/macros/ntuple-per-det-vol.hdf5ls-lh5
  tests/output/macros/ntuple-per-det.hdf5ls-lh5
  tests/output/macros/ntuple-single-table-jag.hdf5ls-lh5
  tests/output/macros/ntuple-single-table-with-tracks-jag.hdf5ls-lh5
  tests/output/macros/ntuple-single-table-with-tracks.hdf5ls
  tests/output/macros/ntuple-single-table-with-tracks.hdf5ls-lh5
  tests/output/macros/ntuple-single-table-with-tracks.mac
  tests/output/macros/ntuple-single-table.hdf5ls
  tests/output/macros/ntuple-single-table.hdf5ls-lh5
  tests/output/macros/ntuple-single-table.mac
  tests/output/run-test-hdf5.sh
  tests/output/run-test-th228-chain.py
  tests/output/visit-hdf5.py
  tests/particlefilter/run-test-basicfilter.py
  tests/particlefilter/run-test-keepvolume.py
  tests/particlefilter/run-test-killvolume.py
  tests/vertex/run-vtx.py
Labels: output

#377 Add output "reshaping" documentation
  docs/manual/output.md
  docs/manual/running.md
Labels: documentation

#379 use a FNV-1a hash to compute process indices
  include/RMGTrackOutputScheme.hh
  src/RMGTrackOutputScheme.cc
Labels: bug, output
