Repository legend-exp/remage, pull requests merged in 2025-01, with the labels that each got.

#206 only store G4TouchableHandle if visualization is enabled
  src/RMGOpticalDetector.cc
Labels: enhancement

#224 Add distance to surface tests
  tests/CMakeLists.txt
  tests/distances/CMakeLists.txt
  tests/distances/gdml/ge-array.gdml
  tests/distances/macros/B99000A.json
  tests/distances/macros/C99000A.json
  tests/distances/macros/P99000A.json
  tests/distances/macros/V99000A.json
  tests/distances/macros/test-ge-distance.mac
  tests/distances/make_ge_gdml.py
  tests/distances/test_ge_distance.py
Labels: validation

#229 Add vis label to all tests opening a GUI
  tests/confinement/CMakeLists.txt
Labels: bug

#240 gps: only set position when requested
  include/RMGGeneratorGPS.hh
Labels: bug
